### ISSUE TITLE
Question span event over multiple days

### ISSUE THREAD

**Issue by tanthammar** [asantibanez/livewire-calendar#1]
Thank you for releasing this package!!

Have some questions:
1. Is there a way to span an event over multiple days?
2. Can I turn of dragging?

**Comment by asantibanez** [comment]
@tanthammar ! thanks for your interest in the package! Just checking this message. Sorry for the delay.

Spanning multiple days is a no go right now. Have to add that.

Turn off dragging? I believe you can. Let me double check.

**Comment by asantibanez** [comment]
Wasn't available but just added some flags to turn on/off day click, event click, event drag and drop events. Thanks @tanthammar!
