### ISSUE TITLE
getting ErrorException `Undefined variable: pollMillis`

### ISSUE THREAD

**Issue by sathia-musso** [asantibanez/livewire-calendar#10]
Hi, I've followed the Readme file but it looks like I can't use the component. I'm on Laravel 8.13 

as far as I understand this should be enough:

    <?php

    namespace App\Http\Livewire;
    use Asantibanez\LivewireCalendar\LivewireCalendar;
    use Illuminate\Support\Collection;
    use Carbon\Carbon;

    class AppointmentsCalendar extends LivewireCalendar
    {

        public function events() : Collection
        {

            return collect([
                [
                    'id' => 1,
                    'title' => 'Breakfast',
                    'description' => 'Pancakes! 🥞',
                    'date' => Carbon::today(),
                ],
                [
                    'id' => 2,
                    'title' => 'Meeting with Pamela',
                    'description' => 'Work stuff',
                    'date' => Carbon::tomorrow(),
                ],
            ]);

        }
    }

I'm then calling 
    <livewire:appointments-calendar />

on my view, but I receive this error 

    ErrorException
    Undefined variable: pollMillis (View: [...]/vendor/asantibanez/livewire-calendar/resources/views/calendar.blade.php)

any idea what might be wrong?

**Comment by asantibanez** [comment]
Hi @sathio 

Please try reinstalling the package and removing any previously exported views. Polling was added afterwards and may be interfering with your current setup.
