### ISSUE TITLE
getting `Unable to find component: [profile.update-profile-information-form]`

### ISSUE THREAD

**Issue by sathia-musso** [asantibanez/livewire-calendar#12]
Hi, as soon as I install your package i get this error, any idea what might be wrong?

it's in 
    vendor/livewire/livewire/src/LivewireManager.php:53

if I remove your package it's fixed immediately, so I suppose it's doing something wrong

**Comment by sathia-musso** [comment]
so, looks like this repo is dead

**Comment by asantibanez** [comment]
Hi @sathio 

`profile.update-profile-information-form` is not part of `livewire-calendar`. Please check your other Livewire components. 

Hope it helps.
