### ISSUE TITLE
Some difficulty in making it work

### ISSUE THREAD

**Issue by myfender** [asantibanez/livewire-calendar#16]
Hi, I have installed the package and made it work but I have some problems.
For example: drag and drop doesn't work. To test the package I installed laravel, liveware, tailwind css and then the calendar from scratch.
The display is correct but drag and drop does not work and neither do the onDayClick, onEventClick and onEventDropped functions.
I try to explain myself better: I move the appointment to another day, the square of the day lights up (it signals it to me) but releasing it does not move it, it returns to its original place.
Of course I added @livewireScripts and @livewireCalendarScripts.
Then the documentation is not clear. For example, I can't get the 3 methods goToPreviousMonth, goToNextMonth and goToCurrentMonth to go.
Also the doc talks about a livewire component: appointments-grid that doesn't seem to exist.
Another thing: is it possible to put appointments with several days in the calendar?
Thanks

**Comment by asantibanez** [comment]
Hi @myfender 

Thanks for your interest in the package.

Have you tried the demo repo? https://github.com/asantibanez/livewire-calendar-demo

Let me know if that helps. 👍
