### ISSUE TITLE
Request: poll for calendar changes

### ISSUE THREAD

**Issue by aaronmyatt** [asantibanez/livewire-calendar#2]
Could we optionally, or by default, add Livewire polling to the calendar?

Adding `wire:poll` here: https://github.com/asantibanez/livewire-calendar/blob/master/resources/views/calendar.blade.php#L1

Seems to the job.

The use case I want to enable is creating events on the same screen as the calendar and have them appear dynamically, see the following video:

https://www.loom.com/share/cffde78ef31a481faef94f77ef63c939

**Comment by jouniikaheimo** [comment]
@aaronmyatt hi can you share your code what you use video ? i want make calendar with repeat events and your video look nice ? and @asantibanez  can you add this livewire v2 support..

**Comment by asantibanez** [comment]
Hello @aaronmyatt . Just added this optional feature. Great suggestion! 

I've also added v2 support.
