### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by roomdada** [asantibanez/livewire-calendar#41]
I get this error when I try to install the package

 Problem 1
    - Root composer.json requires asantibanez/livewire-calendar ^2.1 -> satisfiable by asantibanez/livewire-calendar[2.1.0].
    - asantibanez/livewire-calendar 2.1.0 requires illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.28).

You can also try re-running composer require with an explicit version constraint, e.g. "composer require asantibanez/livewire-calendar:*" to figure out if any version is installable, or "composer require asantibanez/livewire-calendar:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

I have laravel version 9.19 and illuminate/support 9.28. 
thank you in advance for your return.

**Comment by rapgithub** [comment]
I got the same error when I installed but I solved but do not know how! I let you know once I find it out! OK I think the code is not being active maintained and I open a ticket weeks ago and nobody replying yet... sadly

**Comment by roomdada** [comment]
I have noticed this even though my ticket has been open for quite some time. I hope to get an answer to solve the problem as I really need to get it into a project.

@rapgithub  thank you for your reply

**Comment by rapgithub** [comment]
hi sorry for the delay! the package does not support L9 that is why!
so just try this!

open  composer.json and add this line:

```
"repositories": [{ "type": "package", "canonical": false, "package": { "version": "master", "name": "asantibanez/livewire-calendar", "source": { "url": "https://github.com/Butochnikov/livewire-calendar.git", "type": "git", "reference": "master" } } }]
```
Let us mention that the line above has already been forked and updated to work with Laravel 9.

then after you added the line above then run:

composer require asantibanez/livewire-calendar:* 

and viola! the installation will be done without errors!

let me know if now works!
:)

**Comment by roomdada** [comment]
It works perfectly, thank you for your feedback. But since I use zsh I had to run it like this: 
compose req 'asantibanez/livewire-calendar:*' otherwise I get this error zsh: no matches found: asantibanez/livewire-calendar:*

**Comment by rapgithub** [comment]
I am happy that you solved it like this! :) any other thing just let me know because this package is not being updated yet to support L9 and the only solution is that one at the moment!

👍
