### ISSUE TITLE
We are actively maintaining a newer version of this package.

### ISSUE THREAD

**Issue by joshtorres** [asantibanez/livewire-calendar#50]
Package can be found at https://github.com/omnia-digital/livewire-calendar.

Feel free to submit Pull Requests and Issues there and we will address them as soon as possible.

**Comment by yamakrane** [comment]
composer require omnia-digital/livewire-calendar

Throws following error and there no issues section in your project's page.

 Could not find a matching version of package omnia-digital/livewire-calendar. Check the package spelling, your version constraint an  
  d that the package is available in a stability which matches your minimum-stability (stable).

**Comment by joshtorres** [comment]
Sorry about that. I just enabled the Issues section and created your Issue here: https://github.com/omnia-digital/livewire-calendar/issues/5
