### ISSUE TITLE
Pulling in LivewireCalendar breaks Jetstream Livewire components

### ISSUE THREAD

**Issue by mitchtechs** [asantibanez/livewire-calendar#8]
Hi there,

This is a hobby for me and infact, the first issue i've ever submitted on any public repo before, although i have tested this back and forth a few times.

**System Versions (all at time of writing)**
OS: MacOS using Valet
Laravel: Latest
Livewire: Latest

**Replication**
- Brand new laravel app with --jet flag using latest laravel installer
- No additional features added to jetstream in test app
- Compile assets and migrate database
- Load the "Profile" page from the dropdown to prove it works
- Pull in livewire calendar as require from composer following readme
- Try to reload the profile page

**Thoughts**
The error displayed in my app was different, it couldn't locate the declared Livewire Components from the jetstream package, although an error is still thrown with a fresh install
Although i'm not confident enough to make a Pull Request here, i have dismantled the package and made it local (out of the vendor DIR and with no ServiceProvider etc. and it all plays nicely.

**Screenshot**
![jet-livewire-test livewire calendar breaking jetstream](https://user-images.githubusercontent.com/22247493/97127571-e6537e80-1731-11eb-92cc-7c3aa005321e.png)

Hope this is of some help to you!

**Comment by jbajou** [comment]
same issue with a fresh install

**Comment by core45** [comment]
Same here. After installing on fresh Laravel 8 I get this:
Livewire\Exceptions\ComponentNotFoundException
Unable to find component: [navigation-menu]

**Comment by asantibanez** [comment]
This should be fixed in 2.1.0. 

Thanks for your interest in the package!
