### ISSUE TITLE
Feature request: isPast()

### ISSUE THREAD

**Issue by wrabit** [asantibanez/livewire-calendar#9]
Would be nice to alter the display of a day providing it's in the current month, but in the past. 

Have published vendor files for now and added

```
                                        'isToday' => $day->isToday(),
                                        'isPast' => $day->isPast(),
                                        'events' => $getEventsForDay($day, $events),
```

But this really is a nice bit of work! Thanks for sharing it!

**Comment by asantibanez** [comment]
Thanks @wrabit !

Looks interesting. Mind creating a PR with this suggestion?
